### PR TITLE
Use watcher in dev environment

### PR DESCRIPTION
**Pull request by seregazhuk**
When running in `dev` environment uses [PHP-Watcher](https://github.com/seregazhuk/php-watcher) to reload the server once the source code changes. Listens for changes in `config` and `src` folders and `php, yml` files.

This is how it looks like:

[asciicast](https://asciinema.org/a/276698)

I'm not sure if I'm stopping the app correctly 🤔 I've removed all listeners, closed the socket and stopped the kernel. Maybe I've missed something here?

### CODE REVIEW

**Comment by mmoreram** [comment]
I would explore the `--watch` option here. What do you think?

**Comment by seregazhuk** [comment]
>I would explore the --watch option here. What do you think?

So, we don't run the watcher in a `dev` environment by default? Only if the `watch` options is provided, right?

**Comment by mmoreram** [comment]
Yes, I would say something like that, yes.
Basically because people might use the server by hand, and providing a `default` option like this one, seems too aggressive, right?

**Comment by seregazhuk** [comment]
>seems too aggressive, right?

Yes, I suggest making it explicit. Let's make an option `--watch`. If it is provided the watcher starts listening to `src` and `config` folders for changes in `php` and `yaml` files. I think, for now, it is OK. If you need something custom you can change `php-watcher.yml` in the root of the project according to your needs.

**Comment by seregazhuk** [comment]
@mmoreram Done! I have updated the request.

**Comment by mmoreram** [comment]
Once you restart the application, the socket is created once and again, and this turns as an error (non closing the old socket in a port, and connecting to a new one). In order to solve this, we should extract the line `180` of the file `Application` in a new method called `->connectSocket()`, and call it only one time.

**Comment by seregazhuk** [comment]
>Once you restart the application, the socket is created once and again, and this turns as an error (non closing the old socket in a port, and connecting to a new one).

But I'm explicitly closing the socket here 🤔 It doesn't work?

https://github.com/driftphp/server/pull/2/files#diff-c9248b3167fc44af085b81db2e292837R245

**Comment by seregazhuk** [comment]
Closing this PR because this solution doesn't work as expected. Once the server is running all PHP files are already loaded. So, with this implementation even if the application restarts the loaded into memory PHP source code still stays the same. There is no way to run PHP script and live reload itself. 

@mmoreram and I have decided not to use `--watch` option and use a separate console command for running a watcher. Just a syntactic sugar for running a watcher and the server.

**Comment by seregazhuk** [comment]
The better implementation was presented [here](#8).

**Pull request closed without merging**
