### PR TITLE
Added StreamedRequest option

### PR DESCRIPTION
**Pull request by mmoreram**
- Deleted the buffered request as it's done by hand when the transfer
header is not chunked
- Modified tests to keep having the same behavior than before, adding
possible stream in the request

### CODE REVIEW

**Comment by mmoreram** [comment]
We have a problem in this PR.

We deleted the `RequestBodyBufferMiddleware` middleware because we want to allow dynamic request streams instead of buffered ones. This means that, the action that creates buffered streams should be done by hand when is needed (when the header `Transfer-Encoding` is not defined.

The thing is that, as soon as we don't find this header, we should emulate what this deleted `RequestBodyBufferMiddleware` does, like parsing the entre buffered body, including files and $_POST values. All this action is properly done by this middleware and the class `MultipartParser`, marked as *@internal*, so I'm not sure that this is the best approach then.

Will dig in other possible (and dependencies API compliant) solutions before merging.

**Comment by WyriHaximus** [comment]
@mmoreram Assuming you know which routes need streaming and which don't I would suggest having a look at https://github.com/WyriHaximus/reactphp-http-contextual-middleware-runner and set it up like:

```php
$server = new Server([
    /** Other Middleware */
    new ContextualMiddlewareRunner(
        function (ServerRequestInterface $request) {
            if (streaming === true) {
                return true;
            }

            return false;
        },
        [
            // Nothing here because we don't need to buffer when streaming
        ],
        [
            new RequestBodyBufferMiddleware(),
            new RequestBodyParserMiddleware(),
        ]
    )
    /** Other Middleware */
]);
```

**Comment by mmoreram** [comment]
@WyriHaximus we can't assume that, basically because the kernel is completely decoupled from the server, and is the kernel who knows that information...

**Comment by WyriHaximus** [comment]
> @WyriHaximus we can't assume that, basically because the kernel is completely decoupled from the server, and is the kernel who knows that information...

You need to know somehow, one way or the other.

> @WyriHaximus in fact, wouldn't be as easy as check that the header `Transfer-Encoding` exists?

That could be a possibility, another one would be to get the kernel to set an attribute to the request

**Comment by mmoreram** [comment]
@WyriHaximus routes are matched in the kernel, and the dependency flow is only in that direction.

At the end, the server checks the header and applies these two buffer middlewares. If we find a Stream in the body, then all plain values are set to empty and the Stream instance is passed as request attribute (as in Symfony, the object Body can't be a Stream instance)

Merged.

Thanks! :)

**Pull request merged**
