### PR TITLE
Set request based server variables

### PR DESCRIPTION
**Pull request by skydiablo**
see https://github.com/reactphp/http#request-parameters

### CODE REVIEW

**Comment by skydiablo** [comment]
thats not fair! i have run this tests on my local machine, they faild also... but after re-run the same test again, all tests are pass!

**Comment by mmoreram** [comment]
@skydiablo thanks for the PR. I'm not sure what is the purpose of this PR. Can you check please the commit code? Thanks.

**Comment by skydiablo** [comment]
the code is fine... so this code add the request-client-ip/port to every single client request object.

**Comment by mmoreram** [comment]
@skydiablo I've taken this small code, covered with tests, and created a new PR.

Thanks for this addition. The commit has the reference to this PR and to your user.
I appreciate the help.

**Pull request closed without merging**
